Repository cert-manager/openshift-routes, pull requests merged in 2023-12, with the labels that each got.

#47 Fix typo in Helm chart
  deploy/chart/templates/serviceaccount.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#48 Implement private key size annotation
  internal/controller/sync.go
  internal/controller/sync_test.go
Labels: dco-signoff: yes, approved, lgtm, size/L

#44 Upload Helm chart as OCI artifact to GCHR
  .goreleaser.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S
