Repository cert-manager/openshift-routes, pull requests merged in 2023-10, with the labels that each got.

#28 add support for ecdsa keys
  README.md
  go.mod
  go.sum
  hack/test.sh
  internal/controller/sync.go
  internal/controller/sync_test.go
Labels: dco-signoff: yes, size/XXL, approved, lgtm

#24 Document release process and update the versions of the GitHub Actions workflows
  .github/workflows/goreleaser.yaml
  README.md
Labels: dco-signoff: yes, size/M, approved, lgtm

#25 Fix default renewal period
  internal/controller/sync.go
Labels: dco-signoff: yes, approved, lgtm, size/XS
