Repository cert-manager/openshift-routes, pull requests merged in 2024-10, with the labels that each got.

#101 Use Certificates over CertificateRequests (#55 followup)
  deploy/charts/openshift-routes/templates/rbac.yaml
  internal/cmd/app/app.go
  internal/controller/controller.go
  internal/controller/sync.go
  internal/controller/sync_test.go
  internal/controller/util.go
  internal/controller/util_test.go
  make/test-smoke.mk
  test/test-smoke.sh
Labels: dco-signoff: yes, size/XXL, approved, lgtm

#107 [CI] Self-upgrade merging self-upgrade-main into main
  .github/dependabot.yaml
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/repository-base/base-dependabot/.github/dependabot.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, size/M, approved, lgtm

#110 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm

#111 Don't set renew-before if value parses to zero
  internal/controller/sync.go
Labels: dco-signoff: yes, approved, lgtm, size/XS
